const productsTypes = {
    ADD_NEW_PRODUCT_START: 'ADD_NEW_PRODUCT_START',
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    SET_PRODUCTS: 'SET_PRODUCTS',
    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    EDIT_PRODUCT: 'EDIT_PRODUCT',
    EDIT_PRODUCT_START: 'EDIT_PRODUCT_START',
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS'
};

export default productsTypes